export const AGENT_MANIFEST = {
  manifestVersion: "1",
  service: "curio",
  apiVersion: "v1",
  transport: {
    http: {
      apiBasePath: "/api/v1",
      successEnvelope: "{ data }",
      errorEnvelope: "{ error: { code, message, details? } }",
      requestIdHeader: "X-Request-Id",
    },
  },
  toolkit: {
    transport: "mcp-stdio",
    command: "bun run agent:mcp",
    toolNames: [
      "curio_get_manifest",
      "curio_get_health",
      "curio_probe_source",
      "curio_subscribe_source",
      "curio_list_sources",
      "curio_get_source",
      "curio_list_items",
      "curio_get_item",
      "curio_list_quotes",
      "curio_enrich_item",
      "curio_mark_item_read",
      "curio_mark_item_unread",
      "curio_favorite_item",
      "curio_unfavorite_item",
      "curio_save_quote",
      "curio_remove_quote",
      "curio_create_subscription",
      "curio_poll_source",
      "curio_pause_source",
      "curio_resume_source",
      "curio_remove_source",
      "curio_list_destinations",
      "curio_verify_destination",
      "curio_list_routes",
      "curio_create_route",
      "curio_remove_route",
      "curio_list_deliveries",
      "curio_retry_delivery",
    ],
  },
  pagination: {
    query: ["limit", "cursor"],
    limit: { minimum: 1, maximum: 100, default: 50 },
    cursor: "opaque keyset cursor; do not decode or modify",
  },
  safety: {
    confirmationRequiredFor: [
      "subscriptions.remove",
      "routes.remove",
      "items.enrich",
      "items.mark_read",
      "items.mark_unread",
      "items.favorite",
      "items.unfavorite",
      "quotes.create",
      "quotes.remove",
    ],
    confirmationRecommendedFor: [
      "subscriptions.create",
      "subscriptions.ensure",
      "subscriptions.update",
      "destinations.create",
      "destinations.update",
      "destinations.verify",
      "routes.create",
      "routes.update",
      "deliveries.retry",
    ],
    idempotentOperations: [
      "subscriptions.create",
      "subscriptions.ensure",
      "subscriptions.poll",
      "items.mark_read",
      "items.mark_unread",
      "items.favorite",
      "items.unfavorite",
      "quotes.create",
    ],
    secretsNeverReturned: [
      "TELEGRAM_BOT_TOKEN",
      "TELEGRAM_WEBHOOK_SECRET",
      "GITHUB_TOKEN",
      "X_AUTH_TOKEN",
      "X_CT0",
      "X_TWID",
      "X_SESSION",
    ],
  },
  operations: [
    {
      id: "health.read",
      method: "GET",
      path: "/health",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read the backward-compatible service health and uptime response.",
    },
    {
      id: "health.liveness",
      method: "GET",
      path: "/healthz",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read shallow process liveness without external dependency checks.",
    },
    {
      id: "health.readiness",
      method: "GET",
      path: "/readyz",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read local SQLite and migration readiness; non-ready responses are non-2xx.",
    },
    {
      id: "version.read",
      method: "GET",
      path: "/version",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read the service release revision, build time, and schema version.",
    },
    {
      id: "probes.create",
      method: "POST",
      path: "/api/v1/probes",
      class: "external_read",
      confirmation: "none",
      sideEffects: "external_request",
      request: { body: { required: ["url"], optional: [] } },
      description: "Probe a public URL and return validated subscription candidates.",
    },
    {
      id: "subscriptions.ensure",
      method: "POST",
      path: "/api/v1/subscriptions/ensure",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "external_request_and_database",
      request: {
        body: {
          required: ["url"],
          optional: ["pollIntervalMinutes", "intervalMinutes", "metadata"],
        },
      },
      description: "Probe one URL and create or resolve a single subscription candidate.",
    },
    {
      id: "subscriptions.list",
      method: "GET",
      path: "/api/v1/subscriptions",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "List active subscriptions with pagination.",
    },
    {
      id: "subscriptions.create",
      method: "POST",
      path: "/api/v1/subscriptions",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: {
        body: {
          required: ["candidate"],
          optional: ["pollIntervalMinutes", "intervalMinutes", "metadata"],
        },
      },
      description: "Verify a candidate and create or resolve an existing subscription.",
    },
    {
      id: "subscriptions.get",
      method: "GET",
      path: "/api/v1/subscriptions/:id",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read subscription health, cursor, schedule, and metadata.",
    },
    {
      id: "subscriptions.update",
      method: "PATCH",
      path: "/api/v1/subscriptions/:id",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: {
        body: { required: [], optional: ["title", "enabled", "pollIntervalMinutes", "metadata"] },
      },
      description: "Update subscription title, enabled state, schedule, or metadata.",
    },
    {
      id: "subscriptions.remove",
      method: "DELETE",
      path: "/api/v1/subscriptions/:id",
      class: "destructive",
      confirmation: "required",
      sideEffects: "database_soft_delete",
      description: "Soft-delete a subscription while retaining collected items.",
    },
    {
      id: "subscriptions.poll",
      method: "POST",
      path: "/api/v1/subscriptions/:id/poll",
      class: "action",
      confirmation: "none_after_source_confirmation",
      sideEffects: "external_request_and_delivery_enqueue",
      description: "Run the normal poll path immediately for one subscription.",
    },
    {
      id: "subscriptions.items",
      method: "GET",
      path: "/api/v1/subscriptions/:id/items",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read the collected timeline for one subscription.",
    },
    {
      id: "destinations.list",
      method: "GET",
      path: "/api/v1/destinations",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "List delivery destinations without runtime secrets.",
    },
    {
      id: "destinations.create",
      method: "POST",
      path: "/api/v1/destinations",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: {
        body: { required: ["destinationKey", "kind", "config"], optional: ["enabled"] },
      },
      description: "Create a delivery destination using non-secret configuration only.",
    },
    {
      id: "destinations.update",
      method: "PATCH",
      path: "/api/v1/destinations/:id",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: { body: { required: [], optional: ["config", "enabled"] } },
      description: "Update destination configuration or enabled state.",
    },
    {
      id: "destinations.verify",
      method: "POST",
      path: "/api/v1/destinations/:id/verify",
      class: "external_action",
      confirmation: "explicit",
      sideEffects: "external_request",
      description: "Verify a destination with the server-side runtime credential.",
    },
    {
      id: "routes.list",
      method: "GET",
      path: "/api/v1/routes",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "List routes, optionally filtered by subscriptionId.",
    },
    {
      id: "routes.create",
      method: "POST",
      path: "/api/v1/routes",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: {
        body: {
          required: ["subscriptionId", "destinationId"],
          optional: ["enabled", "config"],
        },
      },
      description: "Connect one subscription to one destination.",
    },
    {
      id: "routes.get",
      method: "GET",
      path: "/api/v1/routes/:id",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read one route.",
    },
    {
      id: "routes.update",
      method: "PATCH",
      path: "/api/v1/routes/:id",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: { body: { required: [], optional: ["enabled", "config"] } },
      description: "Update route enabled state or configuration.",
    },
    {
      id: "routes.remove",
      method: "DELETE",
      path: "/api/v1/routes/:id",
      class: "destructive",
      confirmation: "required",
      sideEffects: "database",
      description: "Delete one subscription-to-destination route.",
    },
    {
      id: "items.list",
      method: "GET",
      path: "/api/v1/items",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description:
        "Read the safe global item timeline with Reader state and optional subscriptionId filtering.",
    },
    {
      id: "items.get",
      method: "GET",
      path: "/api/v1/items/:id",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read one bounded canonical article with source metadata and Reader state.",
    },
    {
      id: "items.enrich",
      method: "POST",
      path: "/api/v1/items/:id/enrich",
      class: "external_action",
      confirmation: "explicit",
      sideEffects: "external_request_and_database_snapshot",
      request: { body: { required: [], optional: ["force"] } },
      description: "Fetch and cache bounded static article content for a summary-only item.",
    },
    {
      id: "items.mark_read",
      method: "PATCH",
      path: "/api/v1/items/:id/reader-state",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: { body: { required: ["isRead"], optional: [] } },
      description: "Mark one item read.",
    },
    {
      id: "items.mark_unread",
      method: "PATCH",
      path: "/api/v1/items/:id/reader-state",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: { body: { required: ["isRead"], optional: [] } },
      description: "Mark one item unread.",
    },
    {
      id: "items.favorite",
      method: "PATCH",
      path: "/api/v1/items/:id/reader-state",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: { body: { required: ["isFavorite"], optional: [] } },
      description: "Favorite one item.",
    },
    {
      id: "items.unfavorite",
      method: "PATCH",
      path: "/api/v1/items/:id/reader-state",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: { body: { required: ["isFavorite"], optional: [] } },
      description: "Remove one item from favorites.",
    },
    {
      id: "quotes.list",
      method: "GET",
      path: "/api/v1/quotes",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "List saved exact-source quotes with optional itemId filtering.",
    },
    {
      id: "quotes.create",
      method: "POST",
      path: "/api/v1/items/:id/quotes",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: { body: { required: ["text"], optional: ["note"] } },
      description:
        "Save an exact quote only when the text exists in the current canonical article.",
    },
    {
      id: "quotes.remove",
      method: "DELETE",
      path: "/api/v1/quotes/:id",
      class: "destructive",
      confirmation: "required",
      sideEffects: "database",
      description: "Delete one saved quote without changing its item.",
    },
    {
      id: "deliveries.list",
      method: "GET",
      path: "/api/v1/deliveries",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "List deliveries with optional status filtering.",
    },
    {
      id: "deliveries.retry",
      method: "POST",
      path: "/api/v1/deliveries/:id/retry",
      class: "action",
      confirmation: "explicit",
      sideEffects: "delivery_enqueue",
      description: "Retry an uncertain or permanent-failure delivery.",
    },
  ],
} as const;
