export const AGENT_MANIFEST = {
  manifestVersion: "1",
  service: "curio",
  apiVersion: "v1",
  transport: {
    http: {
      apiBasePath: "/api/v1",
      successEnvelope: "{ data }",
      errorEnvelope: "{ error: { code, message, details? } }",
      requestIdHeader: "X-Request-Id",
    },
  },
  toolkit: {
    transport: "mcp-stdio",
    command: "bun run agent:mcp",
    toolNames: [
      "curio_get_manifest",
      "curio_get_health",
      "curio_probe_source",
      "curio_list_sources",
      "curio_get_source",
      "curio_list_items",
      "curio_create_subscription",
      "curio_poll_source",
      "curio_pause_source",
      "curio_resume_source",
      "curio_remove_source",
      "curio_list_destinations",
      "curio_list_routes",
      "curio_create_route",
      "curio_remove_route",
      "curio_list_deliveries",
      "curio_retry_delivery",
    ],
  },
  pagination: {
    query: ["limit", "cursor"],
    limit: { minimum: 1, maximum: 100, default: 50 },
    cursor: "opaque keyset cursor; do not decode or modify",
  },
  safety: {
    confirmationRequiredFor: ["subscriptions.remove", "routes.remove"],
    confirmationRecommendedFor: [
      "subscriptions.create",
      "subscriptions.update",
      "destinations.create",
      "destinations.update",
      "routes.create",
      "routes.update",
      "deliveries.retry",
    ],
    idempotentOperations: ["subscriptions.create", "subscriptions.poll"],
    secretsNeverReturned: [
      "TELEGRAM_BOT_TOKEN",
      "TELEGRAM_WEBHOOK_SECRET",
      "GITHUB_TOKEN",
      "X_AUTH_TOKEN",
      "X_CT0",
      "X_TWID",
      "X_SESSION",
    ],
  },
  operations: [
    {
      id: "health.read",
      method: "GET",
      path: "/health",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read service health and uptime.",
    },
    {
      id: "probes.create",
      method: "POST",
      path: "/api/v1/probes",
      class: "external_read",
      confirmation: "none",
      sideEffects: "external_request",
      request: { body: { required: ["url"], optional: [] } },
      description: "Probe a public URL and return validated subscription candidates.",
    },
    {
      id: "subscriptions.list",
      method: "GET",
      path: "/api/v1/subscriptions",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "List active subscriptions with pagination.",
    },
    {
      id: "subscriptions.create",
      method: "POST",
      path: "/api/v1/subscriptions",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: {
        body: {
          required: ["candidate"],
          optional: ["pollIntervalMinutes", "intervalMinutes", "metadata"],
        },
      },
      description: "Verify a candidate and create or resolve an existing subscription.",
    },
    {
      id: "subscriptions.get",
      method: "GET",
      path: "/api/v1/subscriptions/:id",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read subscription health, cursor, schedule, and metadata.",
    },
    {
      id: "subscriptions.update",
      method: "PATCH",
      path: "/api/v1/subscriptions/:id",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: {
        body: { required: [], optional: ["title", "enabled", "pollIntervalMinutes", "metadata"] },
      },
      description: "Update subscription title, enabled state, schedule, or metadata.",
    },
    {
      id: "subscriptions.remove",
      method: "DELETE",
      path: "/api/v1/subscriptions/:id",
      class: "destructive",
      confirmation: "required",
      sideEffects: "database_soft_delete",
      description: "Soft-delete a subscription while retaining collected items.",
    },
    {
      id: "subscriptions.poll",
      method: "POST",
      path: "/api/v1/subscriptions/:id/poll",
      class: "action",
      confirmation: "none_after_source_confirmation",
      sideEffects: "external_request_and_delivery_enqueue",
      description: "Run the normal poll path immediately for one subscription.",
    },
    {
      id: "subscriptions.items",
      method: "GET",
      path: "/api/v1/subscriptions/:id/items",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read the collected timeline for one subscription.",
    },
    {
      id: "destinations.list",
      method: "GET",
      path: "/api/v1/destinations",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "List delivery destinations without runtime secrets.",
    },
    {
      id: "destinations.create",
      method: "POST",
      path: "/api/v1/destinations",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: {
        body: { required: ["destinationKey", "kind", "config"], optional: ["enabled"] },
      },
      description: "Create a delivery destination using non-secret configuration only.",
    },
    {
      id: "destinations.update",
      method: "PATCH",
      path: "/api/v1/destinations/:id",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: { body: { required: [], optional: ["config", "enabled"] } },
      description: "Update destination configuration or enabled state.",
    },
    {
      id: "destinations.verify",
      method: "POST",
      path: "/api/v1/destinations/:id/verify",
      class: "external_action",
      confirmation: "explicit",
      sideEffects: "external_request",
      description: "Verify a destination with the server-side runtime credential.",
    },
    {
      id: "routes.list",
      method: "GET",
      path: "/api/v1/routes",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "List routes, optionally filtered by subscriptionId.",
    },
    {
      id: "routes.create",
      method: "POST",
      path: "/api/v1/routes",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: {
        body: {
          required: ["subscriptionId", "destinationId"],
          optional: ["enabled", "config"],
        },
      },
      description: "Connect one subscription to one destination.",
    },
    {
      id: "routes.get",
      method: "GET",
      path: "/api/v1/routes/:id",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read one route.",
    },
    {
      id: "routes.update",
      method: "PATCH",
      path: "/api/v1/routes/:id",
      class: "mutate",
      confirmation: "explicit",
      sideEffects: "database",
      request: { body: { required: [], optional: ["enabled", "config"] } },
      description: "Update route enabled state or configuration.",
    },
    {
      id: "routes.remove",
      method: "DELETE",
      path: "/api/v1/routes/:id",
      class: "destructive",
      confirmation: "required",
      sideEffects: "database",
      description: "Delete one subscription-to-destination route.",
    },
    {
      id: "items.list",
      method: "GET",
      path: "/api/v1/items",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "Read the global item timeline with optional subscriptionId filtering.",
    },
    {
      id: "deliveries.list",
      method: "GET",
      path: "/api/v1/deliveries",
      class: "read",
      confirmation: "none",
      sideEffects: "none",
      description: "List deliveries with optional status filtering.",
    },
    {
      id: "deliveries.retry",
      method: "POST",
      path: "/api/v1/deliveries/:id/retry",
      class: "action",
      confirmation: "explicit",
      sideEffects: "delivery_enqueue",
      description: "Retry an uncertain or permanent-failure delivery.",
    },
  ],
} as const;
